name: npm-publish
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
      - run: npm install -g jdeploy
      - run: ./gradlew build
      - name: jdeploy package
        working-directory: ./build/npm
        run: jdeploy package
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./build/npm/package.json
